### ISSUE TITLE
[1.15.2] Registry Item registered twice (Solved)

### ISSUE THREAD

**Issue by realTIMematrix** [Xratedjunior/Hunter-Mod#2]
Hi,

I'm using:

Minecraft 1.15.2
Forge 31.0.1
HunterMod-1.15.2-1.0.0

get the warning in the logfile:

`[Render thread/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry Item: The object hunter_arrow has been registered twice for the same name huntermod:hunter_arrow.`

Don't know if this can cause problems

**Comment by realTIMematrix** [comment]
Also i did recognize that your mod does not load the config file from defaultconfig folder. Instead it creates one which is not really usefull if there exists one in the defaultconfig folder.
Other mods are using the defaultconfig path from forge to check if there is a defaultconfig and load this instead before creating a new one.

I recognize that this happens only for the Huntermod.toml file, not for the huntermod-server.toml.

For the savegame it works as intended

**Comment by Xratedjunior** [comment]
Hi,

I'm new to this whole GITHUB thing so I'm still looking how to use it properly. I'm aware of the warning but it should not cause problems. I'm looking for a way to fix it but I'm not really sure what is causing it at this moment.

However, I did not know about the config so thank you for telling me! I will look into it.

**Comment by Xratedjunior** [comment]
> Also i did recognize that your mod does not load the config file from defaultconfig folder. Instead it creates one which is not really usefull if there exists one in the defaultconfig folder.
> Other mods are using the defaultconfig path from forge to check if there is a defaultconfig and load this instead before creating a new one.
> 
> I recognize that this happens only for the Huntermod.toml file, not for the huntermod-server.toml.
> 
> For the savegame it works as intended

I fixed the item registries.

Could you maybe elaborate on this? I am not sure what you mean. Or do you have a mod example that uses this technique?

**Comment by realTIMematrix** [comment]
The issue with the twice registerred item is fixed. For the config files you could check the guidebook mod from gigaherz. He creates also two different files at startup.

**Comment by Xratedjunior** [comment]
Thank you!! I will check it out
